// ============================================================================
// hyperbolic.js — a small Poincaré disk model toolkit.
//
// Points are plain {x, y} objects with x^2 + y^2 < 1. Isometries of the
// disk are represented directly as JS functions (point -> point), built
// from two primitives: rotation about the origin, and "translation" (the
// canonical disk automorphism sending 0 to a target point p, which is the
// hyperbolic translation along the geodesic through 0 and p).
//
// The tiling section builds the specific Fuchsian group generated by the
// side-pairings of a regular hyperbolic octagon with vertex angle pi/4 —
// gluing opposite sides of that octagon produces a closed genus-2 surface,
// and the disk tiled by its images under the group is the universal cover.
// ============================================================================

// ---- complex arithmetic on {x, y} points -----------------------------------

function cmul(a, b) {
  return { x: a.x * b.x - a.y * b.y, y: a.x * b.y + a.y * b.x };
}
function cconj(a) {
  return { x: a.x, y: -a.y };
}
function cadd(a, b) {
  return { x: a.x + b.x, y: a.y + b.y };
}
function cdiv(a, b) {
  const d = b.x * b.x + b.y * b.y;
  return { x: (a.x * b.x + a.y * b.y) / d, y: (a.y * b.x - a.x * b.y) / d };
}

export function len(p) {
  return Math.hypot(p.x, p.y);
}
export function polar(r, angle) {
  return { x: r * Math.cos(angle), y: r * Math.sin(angle) };
}

// ---- isometries of the disk -------------------------------------------------

// The Möbius map z -> (z + p) / (1 + conj(p) z). Sends 0 to p; this is the
// hyperbolic translation along the geodesic through 0 and p, by hyperbolic
// distance 2*artanh(|p|).
export function translation(p) {
  const one = { x: 1, y: 0 };
  return (z) => cdiv(cadd(z, p), cadd(one, cmul(cconj(p), z)));
}

export function rotation(theta) {
  const c = { x: Math.cos(theta), y: Math.sin(theta) };
  return (z) => cmul(c, z);
}

// compose(f, g, h)(z) = h(g(f(z))) — applied left to right, matching the
// order generators are written when building a word for the BFS tiling walk.
export function compose(...fns) {
  return (z) => fns.reduce((acc, f) => f(acc), z);
}

// ---- geodesic arcs -----------------------------------------------------------

// Sampled points along the hyperbolic geodesic segment between z1 and z2,
// suitable for a canvas stroke. Geodesics through the origin are Euclidean
// straight lines; every other geodesic is an arc of the unique Euclidean
// circle through z1, z2 and the inversion of z1 (1/conj(z1)) — that circle
// is automatically orthogonal to the unit circle.
export function geodesicPoints(z1, z2, steps = 24) {
  const cross = z1.x * z2.y - z1.y * z2.x;
  if (Math.abs(cross) < 1e-6) {
    const pts = [];
    for (let i = 0; i <= steps; i++) {
      const t = i / steps;
      pts.push({ x: z1.x + (z2.x - z1.x) * t, y: z1.y + (z2.y - z1.y) * t });
    }
    return pts;
  }

  const r1sq = z1.x * z1.x + z1.y * z1.y;
  const z3 = { x: z1.x / r1sq, y: z1.y / r1sq }; // inversion of z1

  const [x1, y1] = [z1.x, z1.y];
  const [x2, y2] = [z2.x, z2.y];
  const [x3, y3] = [z3.x, z3.y];
  const A = x2 - x1, B = y2 - y1, C = x3 - x1, D = y3 - y1;
  const E = A * (x1 + x2) + B * (y1 + y2);
  const F = C * (x1 + x3) + D * (y1 + y3);
  const G = 2 * (A * (y3 - y2) - B * (x3 - x2));
  const cx = (D * E - B * F) / G;
  const cy = (A * F - C * E) / G;
  const radius = Math.hypot(x1 - cx, y1 - cy);

  const a1 = Math.atan2(y1 - cy, x1 - cx);
  const a2 = Math.atan2(y2 - cy, x2 - cx);
  let da = a2 - a1;
  while (da <= -Math.PI) da += 2 * Math.PI;
  while (da > Math.PI) da -= 2 * Math.PI;

  // The circle is orthogonal to the unit circle, so exactly one of the two
  // arcs between z1 and z2 stays inside the disk. Check the short arc's
  // midpoint; if it's outside, take the long way around instead.
  const mid = a1 + da / 2;
  const midPt = { x: cx + radius * Math.cos(mid), y: cy + radius * Math.sin(mid) };
  if (midPt.x * midPt.x + midPt.y * midPt.y > 1) {
    da = da > 0 ? da - 2 * Math.PI : da + 2 * Math.PI;
  }

  const pts = [];
  for (let i = 0; i <= steps; i++) {
    const a = a1 + (da * i) / steps;
    pts.push({ x: cx + radius * Math.cos(a), y: cy + radius * Math.sin(a) });
  }
  return pts;
}

// A full geodesic *line* (boundary to boundary) through point p in the
// direction angle theta, as {start, end} ideal points on the unit circle
// plus a sampled point list for stroking. Built by taking the diameter
// through the origin at angle theta (a geodesic) and moving it to pass
// through p via the disk automorphism that sends 0 -> p.
export function geodesicLineThrough(p, theta, steps = 48) {
  const toP = translation(p);
  const pts = [];
  for (let i = 0; i <= steps; i++) {
    // Sample the open interval (-1, 1) on the diameter, biased toward the
    // ends so the image arc's dense curvature near the boundary is smooth.
    const t = -1 + (2 * i) / steps;
    const s = Math.sign(t) * (1 - Math.cos((Math.abs(t) * Math.PI) / 2)); // ease toward ±1
    const raw = polar(0.9999 * Math.abs(s), s >= 0 ? theta : theta + Math.PI);
    pts.push(toP(raw));
  }
  return pts;
}

// ---- regular octagon / genus-2 surface tiling --------------------------------

const SIDES = 8;
const VERTEX_ANGLE = Math.PI / 4; // 8 octagons meet at every vertex

// Right hyperbolic triangle identities for the triangle (center,
// edge-midpoint, vertex), right angle at the edge midpoint:
//   angle at center = pi/SIDES, angle at vertex = VERTEX_ANGLE/2
// cosh(hypotenuse) = cot(A) cot(B)          -> circumradius (center to vertex)
// cosh(leg adjacent to vertex) = cos(B)/sin(A) -> apothem (center to edge midpoint)
const CIRCUMRADIUS = Math.acosh(1 / (Math.tan(Math.PI / SIDES) * Math.tan(VERTEX_ANGLE / 2)));
const APOTHEM_DIST = Math.acosh(Math.cos(VERTEX_ANGLE / 2) / Math.sin(Math.PI / SIDES));

export const R_VERTEX = Math.tanh(CIRCUMRADIUS / 2);
const TRANSLATION_MAG = Math.tanh(APOTHEM_DIST);

export function octagonVertices() {
  const verts = [];
  for (let k = 0; k < SIDES; k++) {
    verts.push(polar(R_VERTEX, (k * 2 * Math.PI) / SIDES));
  }
  return verts;
}

function edgeMidAngle(k) {
  return (k + 0.5) * ((2 * Math.PI) / SIDES);
}

// One generator per side: SIDE_GENERATORS[k] carries the octagon across
// edge k onto its neighbor. Because opposite edges are glued to each other,
// SIDE_GENERATORS[k + 4] is automatically the inverse of SIDE_GENERATORS[k].
export const SIDE_GENERATORS = Array.from({ length: SIDES }, (_, k) =>
  translation(polar(TRANSLATION_MAG, edgeMidAngle(k)))
);

// BFS over group words up to maxDepth, skipping immediate backtracking
// (applying a generator right after its inverse), pruning branches whose
// image has drifted too close to the boundary to be worth drawing. Returns
// a flat list of octagon vertex-sets, one per tile (including the base tile).
export function generateTiling(maxDepth = 3, radiusCutoff = 0.995) {
  const base = octagonVertices();
  const identity = (z) => z;
  const tiles = [{ verts: base, depth: 0 }];
  let frontier = [{ transform: identity, lastGen: -1 }];

  for (let d = 0; d < maxDepth; d++) {
    const next = [];
    for (const node of frontier) {
      for (let g = 0; g < SIDES; g++) {
        if (node.lastGen !== -1 && g === (node.lastGen + SIDES / 2) % SIDES) continue;
        const transform = compose(SIDE_GENERATORS[g], node.transform);
        const verts = base.map(transform);
        const maxR = Math.max(...verts.map(len));
        if (maxR > radiusCutoff) continue;
        tiles.push({ verts, depth: d + 1 });
        next.push({ transform, lastGen: g });
      }
    }
    frontier = next;
  }
  return tiles;
}
